/* tslint:disable */
/* eslint-disable */
/**
 * AgentLabs API
 * Build AI Agents in minutes, not months.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserDto
 */
export interface RegisterUserDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    name: string;
}

/**
 * Check if a given object implements the RegisterUserDto interface.
 */
export function instanceOfRegisterUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RegisterUserDtoFromJSON(json: any): RegisterUserDto {
    return RegisterUserDtoFromJSONTyped(json, false);
}

export function RegisterUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'name': json['name'],
    };
}

export function RegisterUserDtoToJSON(value?: RegisterUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'name': value.name,
    };
}

