/* tslint:disable */
/* eslint-disable */
/**
 * AgentLabs API
 * Build AI Agents in minutes, not months.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SanitizedUserResponse
 */
export interface SanitizedUserResponse {
    /**
     * 
     * @type {string}
     * @memberof SanitizedUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SanitizedUserResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SanitizedUserResponse
     */
    name: string;
}

/**
 * Check if a given object implements the SanitizedUserResponse interface.
 */
export function instanceOfSanitizedUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function SanitizedUserResponseFromJSON(json: any): SanitizedUserResponse {
    return SanitizedUserResponseFromJSONTyped(json, false);
}

export function SanitizedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SanitizedUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
    };
}

export function SanitizedUserResponseToJSON(value?: SanitizedUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'name': value.name,
    };
}

