FROM node:20-alpine3.17 as dev

WORKDIR /app

VOLUME [ "/app" ]

COPY ./scripts/docker-entrypoint.dev.sh /docker-entrypoint.dev.sh

# We install Java because it's needed for OpenAPI CLI Generator to work.
RUN apk add openjdk11


ENTRYPOINT [ "sh", "/docker-entrypoint.dev.sh" ]
