FROM node:20-alpine3.17 

WORKDIR /app

VOLUME [ "/app" ]

# IMPORTANT:
# As svelte kit uses vite under the hood, which itself use esbuild, it is necessary to install the deps from inside
# the container as esbuild is a native dependency and it needs to be compiled for the target platform.

ENTRYPOINT [ "sh", "-c", "npm install && npm run dev -- --port 3000 --host" ]
